Policies: Request circulation policies
inveniosoftware/invenio-circulation pull request #98
Opened 2019-02-25 13:38 UTC by BadrAly

* NEW Adds request circulation policies

Co-authored-by: Aly Badr <aly.badr@rero.ch>
Co-authored-by: bertrand Zuchuat <bertrand.zuchuat@rero.ch>

2019-02-25 15:36 UTC, zzacharo requested changes

2019-02-25 15:36 UTC, zzacharo commented on invenio_circulation/config.py
> +    is_can_request, is_item_available, is_loan_duration_valid, item_exists, \
Probably `can_be_requested`?

2019-02-25 15:36 UTC, zzacharo commented on invenio_circulation/utils.py
> +def is_can_request(record_pid=None, request_level=None):
Same here.

2019-02-25 15:36 UTC, zzacharo commented on invenio_circulation/errors.py
> +class RecordCanNotSatisfyAction(CirculationException):
Probably `RecordCannotBeRequested`?

2019-02-25 16:00 UTC, ntarocco commented
@BadrAly I want to give you our point of view on this, because we had similar thoughts.

The `CREATED` status is a "fake" one: we need a starting point to perform the first transition to `REQUESTED` or to another state, but ideally we should never have loans in state `CREATED`.

Are you planning to build a UI to find all CREATED and clean them up at certain point?

In our case, we decided that we never want this state, so we actually check in ILS, before, if the Item can be requested and then we perform in one single atomic operation:
```
# check first if loan can be created and requested for the given item
loan = Loan.create()  # status will be CREATED
circulation.trigger(
    loan, **dict(params, trigger="request")
)
# status will be REQUESTED
```
Basically for us is or `REQUESTED`, or it does not exist in our db.

2019-02-26 09:31 UTC, BadrAly commented
@ntarocco : Could you please merge this PR?
We already manage the  `CREATED` status as you explained on our UI. @jma will add more to this later.

2019-02-26 13:27 UTC, ntarocco approved these changes

2019-02-26 13:28 UTC, merged